"""
Demo AI Service — Single authoritative backend source of truth for research demo cases.
Every demo case defines consistent CT imaging, metadata, nodules, cropped thumbnails,
calibrated measurements, Brock/PanCan risk assessment, 3D coordinates, patient context, and recent tests.

IMPORTANT: All outputs are explicitly labeled is_demo=True.
This service does NOT perform uncalibrated fake inferences.
"""
from typing import Dict, Any, Optional, List

DEMO_CASES: Dict[str, Dict[str, Any]] = {
    "DEMO-001": {
        "id": "DEMO-001",
        "label": "DEMO-001 — Solitary Small Nodule",
        "description": "5.4 mm solid nodule in Right Upper Lobe. Low suspicion (7.2% Brock risk, Lung-RADS 3).",
        "scenario": "Low",
        "primary_risk_category": "low",
        "dominant_size_mm": 5.4,
        "input_type": "volumetric_ct",
        "analysis_mode": "demo",
        "scan_metadata": {
            "modality": "CT",
            "patient_id_anon": "PS-2026-001",
            "study_date": "2026-01-12",
            "series_description": "CHEST CT (DICOM)",
            "slice_count": 312,
            "slice_thickness_mm": 1.0,
            "pixel_spacing_x": 0.703,
            "pixel_spacing_y": 0.703,
            "rows": 512,
            "cols": 512,
            "scan_quality": "good",
            "quality_notes": [
                "Adequate resolution (1.0 mm)",
                "Full thoracic coverage",
                "No motion artifacts detected",
            ],
        },
        "patient_context": {
            "medical_history": {
                "smoking_status": "never",
                "pack_years": 0,
                "family_history_lung_cancer": "no",
                "copd_emphysema": "no",
                "previous_pulmonary_nodules": "no",
                "relevant_surgeries": "None",
                "relevant_medications": "None",
            },
            "recent_tests": [
                {
                    "test_type": "Chest X-Ray",
                    "test_date": "2025-08-14",
                    "summary": "Normal cardio-thoracic contours. No clear focal consolidation or infiltrates.",
                    "doctor_note": "Annual routine check-up.",
                },
                {
                    "test_type": "Pulmonary Function Test",
                    "test_date": "2025-09-03",
                    "summary": "FEV1 96% predicted, FVC 98% predicted. Normal spirometry.",
                    "doctor_note": "Good baseline lung volumes.",
                },
            ],
        },
        "nodules": [
            {
                "nodule_index": 1,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 380.0,
                "coord_y": 320.0,
                "coord_z": 230.0,
                "max_diameter_mm": 5.4,
                "min_diameter_mm": 4.8,
                "mean_diameter_mm": 5.1,
                "volume_mm3": 82.5,
                "mean_hu": 48.0,
                "median_hu": 45.0,
                "min_hu": -85.0,
                "max_hu": 162.0,
                "std_hu": 36.4,
                "density_type": "solid",
                "sphericity": 0.84,
                "elongation": 1.12,
                "surface_area_mm2": 92.0,
                "compactness": 0.81,
                "margin_type": "smooth",
                "spiculation_detected": False,
                "lung_side": "left",
                "lung_lobe": "LLL",
                "position_type": "peripheral",
                "axial_slice": 230,
                "coronal_slice": 142,
                "sagittal_slice": 380,
                "thumbnail_url": "/thumbnails/nodule_demo1_1.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.072,
                    "risk_category": "low",
                    "lung_rads_category": "3",
                    "lung_rads_recommendation": "6-month follow-up Low-Dose CT recommended to verify stability.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Nodule Size", "score": 0.32, "level": "low", "description": "5.4 mm — small baseline diameter"},
                        {"name": "location", "display_name": "Lower-Lobe Location", "score": 0.22, "level": "low", "description": "Left lower lobe baseline location"},
                        {"name": "density", "display_name": "Solid Density", "score": 0.28, "level": "low", "description": "Solid attenuation pattern"},
                        {"name": "margin", "display_name": "Smooth Margins", "score": 0.12, "level": "low", "description": "Well-circumscribed margins with no spiculation"},
                    ],
                    "clinical_inputs": {"age": 58, "sex": "female", "smoking_history": False, "pack_years": 0},
                    "is_demo": True,
                },
            }
        ],
        "summary": {
            "nodule_count": 1,
            "largest_nodule_mm": 5.4,
            "highest_risk_pct": 7.2,
            "lung_rads_overall": "3",
            "conclusion": "Single 5.4 mm solid nodule in Left Lower Lobe. Estimated malignancy probability 7.2% (Low Suspicion). ACR Lung-RADS Category 3 — 6-month CT follow-up recommended.",
        },
    },

    "DEMO-002": {
        "id": "DEMO-002",
        "label": "DEMO-002 — Multiple Nodules (Dominant Intermediate)",
        "description": "Three nodules: dominant 8.6 mm intermediate lesion in RLL (28.5% Brock risk, Lung-RADS 4A), 5.6 mm in RUL, 4.1 mm in LUL.",
        "scenario": "Intermediate",
        "primary_risk_category": "intermediate",
        "dominant_size_mm": 8.6,
        "input_type": "volumetric_ct",
        "analysis_mode": "demo",
        "scan_metadata": {
            "modality": "CT",
            "patient_id_anon": "PS-2026-002",
            "study_date": "2026-02-18",
            "series_description": "CHEST CT (DICOM)",
            "slice_count": 512,
            "slice_thickness_mm": 1.0,
            "pixel_spacing_x": 0.703,
            "pixel_spacing_y": 0.703,
            "rows": 512,
            "cols": 512,
            "scan_quality": "good",
            "quality_notes": [
                "High-contrast reconstruction",
                "Breath-hold achieved",
                "Full lung parenchyma coverage",
            ],
        },
        "patient_context": {
            "medical_history": {
                "smoking_status": "former",
                "pack_years": 20,
                "family_history_lung_cancer": "no",
                "copd_emphysema": "yes",
                "previous_pulmonary_nodules": "yes",
                "relevant_surgeries": "Appendectomy (1988)",
                "relevant_medications": "Albuterol inhaler PRN",
                "other_history": "Former smoker, quit 5 years ago.",
            },
            "recent_tests": [
                {
                    "test_type": "Previous CT",
                    "test_date": "2025-02-14",
                    "summary": "Baseline CT showed 7.2 mm solitary nodule in RLL. Follow-up recommended in 12 months.",
                    "doctor_note": "Nodule #1 grew from 7.2 mm to 8.6 mm (+19% diameter, stable/indolent kinetics).",
                },
                {
                    "test_type": "PFT",
                    "test_date": "2025-10-10",
                    "summary": "Mild obstructive ventilatory impairment (FEV1/FVC 69%).",
                    "doctor_note": "Mild centrilobular emphysema noted on chest CT.",
                },
            ],
        },
        "nodules": [
            {
                "nodule_index": 1,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 160.0,
                "coord_y": 345.0,
                "coord_z": 245.0,
                "max_diameter_mm": 8.6,
                "min_diameter_mm": 7.4,
                "mean_diameter_mm": 8.0,
                "volume_mm3": 332.0,
                "mean_hu": -18.0,
                "median_hu": -10.0,
                "min_hu": -320.0,
                "max_hu": 145.0,
                "std_hu": 38.5,
                "density_type": "part_solid",
                "sphericity": 0.72,
                "elongation": 1.24,
                "surface_area_mm2": 232.0,
                "compactness": 0.81,
                "margin_type": "lobulated",
                "spiculation_detected": False,
                "lung_side": "right",
                "lung_lobe": "RLL",
                "position_type": "peripheral",
                "axial_slice": 245,
                "coronal_slice": 238,
                "sagittal_slice": 160,
                "thumbnail_url": "/thumbnails/nodule_demo2_1.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.285,
                    "risk_category": "intermediate",
                    "lung_rads_category": "4A",
                    "lung_rads_recommendation": "3-month Low-Dose CT follow-up or PET/CT correlation recommended.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Nodule Size", "score": 0.62, "level": "moderate", "description": "8.6 mm diameter — intermediate threshold"},
                        {"name": "density", "display_name": "Part-Solid Attenuation", "score": 0.58, "level": "moderate", "description": "Part-solid composition with ground-glass halo"},
                        {"name": "margin", "display_name": "Lobulated Margin", "score": 0.45, "level": "moderate", "description": "Mild lobulation without prominent spiculation"},
                        {"name": "history", "display_name": "Smoking History", "score": 0.40, "level": "moderate", "description": "20 pack-year former smoking history"},
                    ],
                    "clinical_inputs": {"age": 62, "sex": "male", "smoking_history": True, "pack_years": 20, "emphysema": True, "family_history_lung_cancer": False},
                    "is_demo": True,
                },
            },
            {
                "nodule_index": 2,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 150.0,
                "coord_y": 175.0,
                "coord_z": 175.0,
                "max_diameter_mm": 5.6,
                "min_diameter_mm": 4.9,
                "mean_diameter_mm": 5.2,
                "volume_mm3": 91.0,
                "mean_hu": 36.0,
                "median_hu": 32.0,
                "min_hu": -110.0,
                "max_hu": 140.0,
                "std_hu": 32.1,
                "density_type": "solid",
                "sphericity": 0.82,
                "elongation": 1.15,
                "surface_area_mm2": 98.0,
                "compactness": 0.85,
                "margin_type": "smooth",
                "spiculation_detected": False,
                "lung_side": "right",
                "lung_lobe": "RUL",
                "position_type": "peripheral",
                "axial_slice": 175,
                "coronal_slice": 195,
                "sagittal_slice": 150,
                "thumbnail_url": "/thumbnails/nodule_demo2_2.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.142,
                    "risk_category": "low",
                    "lung_rads_category": "3",
                    "lung_rads_recommendation": "6-month Low-Dose CT follow-up.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Nodule Size", "score": 0.38, "level": "low", "description": "5.6 mm diameter"},
                        {"name": "location", "display_name": "Upper Lobe", "score": 0.44, "level": "moderate", "description": "Right Upper Lobe"},
                    ],
                    "is_demo": True,
                },
            },
            {
                "nodule_index": 3,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 355.0,
                "coord_y": 175.0,
                "coord_z": 175.0,
                "max_diameter_mm": 4.1,
                "min_diameter_mm": 3.7,
                "mean_diameter_mm": 3.9,
                "volume_mm3": 36.0,
                "mean_hu": 54.0,
                "median_hu": 51.0,
                "min_hu": -75.0,
                "max_hu": 142.0,
                "std_hu": 26.5,
                "density_type": "solid",
                "sphericity": 0.89,
                "elongation": 1.09,
                "surface_area_mm2": 52.0,
                "compactness": 0.92,
                "margin_type": "smooth",
                "spiculation_detected": False,
                "lung_side": "left",
                "lung_lobe": "LUL",
                "position_type": "peripheral",
                "axial_slice": 175,
                "coronal_slice": 172,
                "sagittal_slice": 355,
                "thumbnail_url": "/thumbnails/nodule_demo2_3.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.065,
                    "risk_category": "low",
                    "lung_rads_category": "2",
                    "lung_rads_recommendation": "Routine annual Low-Dose CT screening.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Nodule Size", "score": 0.18, "level": "low", "description": "4.1 mm — small baseline nodule"},
                    ],
                    "is_demo": True,
                },
            },
        ],
        "summary": {
            "nodule_count": 3,
            "largest_nodule_mm": 8.6,
            "highest_risk_pct": 28.5,
            "lung_rads_overall": "4A",
            "conclusion": "Three pulmonary nodules detected. Dominant Nodule #1 (8.6 mm, part-solid, RLL) exhibits intermediate malignancy risk (28.5%). ACR Lung-RADS 4A — 3-month CT follow-up or PET/CT correlation recommended.",
        },
    },

    "DEMO-003": {
        "id": "DEMO-003",
        "label": "DEMO-003 — High-Risk Spiculated Mass",
        "description": "16.4 mm spiculated part-solid lesion with documented growth. Higher suspicion (86.4% Brock risk, Lung-RADS 4X).",
        "scenario": "Higher Suspicion",
        "primary_risk_category": "higher",
        "dominant_size_mm": 16.4,
        "input_type": "volumetric_ct",
        "analysis_mode": "demo",
        "scan_metadata": {
            "modality": "CT",
            "patient_id_anon": "PS-2026-003",
            "study_date": "2026-03-04",
            "series_description": "CHEST CT (DICOM)",
            "slice_count": 480,
            "slice_thickness_mm": 1.0,
            "pixel_spacing_x": 0.65,
            "pixel_spacing_y": 0.65,
            "rows": 512,
            "cols": 512,
            "scan_quality": "good",
            "quality_notes": [
                "Diagnostic quality",
                "Intense peripheral vascular markings",
                "No motion artifact",
            ],
        },
        "patient_context": {
            "medical_history": {
                "smoking_status": "current",
                "pack_years": 45,
                "family_history_lung_cancer": "yes",
                "copd_emphysema": "yes",
                "previous_pulmonary_nodules": "yes",
                "relevant_surgeries": "None",
                "relevant_medications": "Tiotropium, Atorvastatin",
                "other_history": "Unexplained 4 kg weight loss over last 3 months.",
            },
            "recent_tests": [
                {
                    "test_type": "Prior CT",
                    "test_date": "2025-09-10",
                    "summary": "11.2 mm part-solid lesion noted in Right Upper Lobe. Recommended 3-6 month follow-up.",
                    "doctor_note": "Interval increase from 11.2 mm to 16.4 mm (VDT = 198 days, rapid growth).",
                },
                {
                    "test_type": "Biopsy/Pathology",
                    "test_date": "Pending",
                    "summary": "CT-guided transthoracic needle biopsy pending radiologist consult.",
                    "doctor_note": "Urgent staging recommended.",
                },
            ],
        },
        "nodules": [
            {
                "nodule_index": 1,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 145.0,
                "coord_y": 250.0,
                "coord_z": 160.0,
                "max_diameter_mm": 16.4,
                "min_diameter_mm": 13.2,
                "mean_diameter_mm": 14.8,
                "volume_mm3": 1820.0,
                "mean_hu": 34.0,
                "median_hu": 28.0,
                "min_hu": -280.0,
                "max_hu": 210.0,
                "std_hu": 62.1,
                "density_type": "part_solid",
                "sphericity": 0.52,
                "elongation": 1.54,
                "surface_area_mm2": 680.0,
                "compactness": 0.64,
                "margin_type": "spiculated",
                "spiculation_detected": True,
                "lung_side": "right",
                "lung_lobe": "RUL",
                "position_type": "peripheral",
                "axial_slice": 160,
                "coronal_slice": 160,
                "sagittal_slice": 145,
                "thumbnail_url": "/thumbnails/nodule_demo3_1.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.864,
                    "risk_category": "very_high",
                    "lung_rads_category": "4X",
                    "lung_rads_recommendation": "Urgent multidisciplinary oncology consultation, PET/CT staging, and tissue biopsy recommended.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Lesion Size (>15 mm)", "score": 0.95, "level": "high", "description": "16.4 mm diameter carries elevated risk of invasive malignancy"},
                        {"name": "spiculation", "display_name": "Coronary Spiculation", "score": 0.92, "level": "high", "description": "Prominent radiating spicules and pleural tagging"},
                        {"name": "growth", "display_name": "Rapid Volume Doubling", "score": 0.90, "level": "high", "description": "VDT of 198 days is consistent with rapid malignant kinetics"},
                        {"name": "clinical", "display_name": "Age & Pack-Years", "score": 0.85, "level": "high", "description": "Age 71, 45 pack-years current smoking, emphysema, weight loss"},
                    ],
                    "clinical_inputs": {"age": 71, "sex": "male", "smoking_history": True, "pack_years": 45, "emphysema": True, "family_history_lung_cancer": True},
                    "is_demo": True,
                },
            }
        ],
        "summary": {
            "nodule_count": 1,
            "largest_nodule_mm": 16.4,
            "highest_risk_pct": 86.4,
            "lung_rads_overall": "4X",
            "conclusion": "16.4 mm spiculated part-solid lesion in Right Upper Lobe. Estimated malignancy probability 86.4% (Higher Suspicion). Demonstrates rapid interval growth. ACR Lung-RADS 4X — Immediate thoracic oncology referral and tissue biopsy warranted.",
        },
    },

    "DEMO-004": {
        "id": "DEMO-004",
        "label": "DEMO-004 — Screening CT (No Significant Nodules)",
        "description": "Normal low-dose screening thoracic CT. ACR Lung-RADS Category 1 (Negative, 0 nodules).",
        "scenario": "Negative / No Significant Nodule",
        "primary_risk_category": "unassessed",
        "dominant_size_mm": None,
        "input_type": "volumetric_ct",
        "analysis_mode": "demo",
        "scan_metadata": {
            "modality": "CT",
            "patient_id_anon": "PS-2026-004",
            "study_date": "2026-02-22",
            "series_description": "CHEST CT (DICOM)",
            "slice_count": 320,
            "slice_thickness_mm": 1.0,
            "pixel_spacing_x": 0.703,
            "pixel_spacing_y": 0.703,
            "rows": 512,
            "cols": 512,
            "scan_quality": "good",
            "quality_notes": [
                "Adequate lung expansion",
                "Complete parenchyma visualization",
                "No actionable findings",
            ],
        },
        "patient_context": {
            "medical_history": {
                "smoking_status": "never",
                "pack_years": 0,
                "family_history_lung_cancer": "no",
                "copd_emphysema": "no",
                "previous_pulmonary_nodules": "no",
                "relevant_surgeries": "None",
                "relevant_medications": "None",
            },
            "recent_tests": [
                {
                    "test_type": "Chest X-Ray",
                    "test_date": "2025-01-12",
                    "summary": "Normal screening thoracic radiograph. Clear costophrenic angles.",
                    "doctor_note": "Annual occupational health clearance.",
                }
            ],
        },
        "nodules": [],
        "summary": {
            "nodule_count": 0,
            "largest_nodule_mm": None,
            "highest_risk_pct": None,
            "lung_rads_overall": "1",
            "conclusion": "Screening thoracic CT demonstrates clear bilateral lung parenchyma without actionable pulmonary nodule or focal consolidation. ACR Lung-RADS Category 1 (Negative). Routine annual screening recommended.",
        },
    },

    "DEMO-005": {
        "id": "DEMO-005",
        "label": "DEMO-005 — Multiple Nodules (Mixed Suspicion)",
        "description": "Three nodules of mixed risk: dominant 14.2 mm Higher Suspicion lesion in RUL (78.0%), 7.8 mm Intermediate in RLL (32.0%), 4.5 mm Low in LLL (8.0%).",
        "scenario": "Mixed Multiple Nodules",
        "primary_risk_category": "higher",
        "dominant_size_mm": 14.2,
        "input_type": "volumetric_ct",
        "analysis_mode": "demo",
        "scan_metadata": {
            "modality": "CT",
            "patient_id_anon": "PS-2026-005",
            "study_date": "2026-02-28",
            "series_description": "CHEST CT (DICOM)",
            "slice_count": 450,
            "slice_thickness_mm": 1.0,
            "pixel_spacing_x": 0.703,
            "pixel_spacing_y": 0.703,
            "rows": 512,
            "cols": 512,
            "scan_quality": "good",
            "quality_notes": [
                "Full thoracic coverage",
                "High contrast resolution",
                "No motion artifact",
            ],
        },
        "patient_context": {
            "medical_history": {
                "smoking_status": "former",
                "pack_years": 30,
                "family_history_lung_cancer": "yes",
                "copd_emphysema": "yes",
                "previous_pulmonary_nodules": "yes",
                "relevant_surgeries": "None",
                "relevant_medications": "Symbicort inhaler",
                "other_history": "Quit smoking 3 years ago.",
            },
            "recent_tests": [
                {
                    "test_type": "Previous CT",
                    "test_date": "2025-05-18",
                    "summary": "Two sub-centimeter nodules observed; surveillance CT requested at 9-12 months.",
                    "doctor_note": "Interval enlargement in RUL lesion; follow-up demonstrates mixed-risk progression.",
                },
            ],
        },
        "nodules": [
            {
                "nodule_index": 1,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 144.0,
                "coord_y": 246.0,
                "coord_z": 58.0,
                "max_diameter_mm": 14.2,
                "min_diameter_mm": 11.8,
                "mean_diameter_mm": 13.0,
                "volume_mm3": 1240.0,
                "mean_hu": 15.2,
                "median_hu": 18.0,
                "min_hu": -80.0,
                "max_hu": 175.0,
                "std_hu": 42.0,
                "density_type": "part_solid",
                "sphericity": 0.72,
                "elongation": 1.35,
                "surface_area_mm2": 520.0,
                "compactness": 0.70,
                "margin_type": "spiculated",
                "spiculation_detected": True,
                "lung_side": "right",
                "lung_lobe": "RUL",
                "position_type": "peripheral",
                "axial_slice": 58,
                "coronal_slice": 246,
                "sagittal_slice": 144,
                "thumbnail_url": "/thumbnails/nodule_demo5_1.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.780,
                    "risk_category": "very_high",
                    "lung_rads_category": "4X",
                    "lung_rads_recommendation": "Multidisciplinary thoracic oncology consultation, diagnostic PET/CT, and tissue biopsy recommended.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Nodule Size (14.2 mm)", "score": 0.88, "level": "high", "description": "14.2 mm dominant part-solid mass in upper lobe"},
                        {"name": "spiculation", "display_name": "Spiculated Contour", "score": 0.82, "level": "high", "description": "Irregular spiculated boundary with pleural tagging"},
                        {"name": "density", "display_name": "Part-Solid Attenuation", "score": 0.76, "level": "high", "description": "Significant solid component with surrounding ground glass"},
                    ],
                    "clinical_inputs": {"age": 67, "sex": "male", "smoking_history": True, "pack_years": 30, "emphysema": True, "family_history_lung_cancer": True},
                    "is_demo": True,
                },
            },
            {
                "nodule_index": 2,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 212.0,
                "coord_y": 208.0,
                "coord_z": 58.0,
                "max_diameter_mm": 8.2,
                "min_diameter_mm": 7.0,
                "mean_diameter_mm": 7.6,
                "volume_mm3": 290.0,
                "mean_hu": 28.0,
                "median_hu": 24.0,
                "min_hu": -120.0,
                "max_hu": 150.0,
                "std_hu": 36.0,
                "density_type": "solid",
                "sphericity": 0.74,
                "elongation": 1.20,
                "surface_area_mm2": 195.0,
                "compactness": 0.79,
                "margin_type": "lobulated",
                "spiculation_detected": False,
                "lung_side": "left",
                "lung_lobe": "LUL",
                "position_type": "perihilar",
                "axial_slice": 58,
                "coronal_slice": 208,
                "sagittal_slice": 212,
                "thumbnail_url": "/thumbnails/nodule_demo5_2.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.340,
                    "risk_category": "intermediate",
                    "lung_rads_category": "4A",
                    "lung_rads_recommendation": "Intermediate suspicion. 3-month follow-up diagnostic chest CT recommended.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Intermediate Size (8.2 mm)", "score": 0.58, "level": "moderate", "description": "8.2 mm solid perihilar nodule"},
                        {"name": "margin", "display_name": "Lobulated Margin", "score": 0.48, "level": "moderate", "description": "Lobulated contour requiring growth surveillance"},
                    ],
                    "is_demo": True,
                },
            },
            {
                "nodule_index": 3,
                "detection_confidence": None,
                "is_demo": True,
                "coord_x": 375.0,
                "coord_y": 250.0,
                "coord_z": 58.0,
                "max_diameter_mm": 4.5,
                "min_diameter_mm": 4.0,
                "mean_diameter_mm": 4.25,
                "volume_mm3": 48.0,
                "mean_hu": 52.0,
                "median_hu": 48.0,
                "min_hu": -60.0,
                "max_hu": 138.0,
                "std_hu": 28.0,
                "density_type": "solid",
                "sphericity": 0.88,
                "elongation": 1.08,
                "surface_area_mm2": 64.0,
                "compactness": 0.90,
                "margin_type": "smooth",
                "spiculation_detected": False,
                "lung_side": "left",
                "lung_lobe": "LLL",
                "position_type": "peripheral",
                "axial_slice": 58,
                "coronal_slice": 250,
                "sagittal_slice": 375,
                "thumbnail_url": "/thumbnails/nodule_demo5_3.jpg",
                "risk": {
                    "source": "curated_demo_profile",
                    "model_name": "brock_pancan_demo",
                    "risk_probability": 0.080,
                    "risk_category": "low",
                    "lung_rads_category": "2",
                    "lung_rads_recommendation": "Benign appearance. Routine annual Low-Dose CT screening.",
                    "contributing_factors": [
                        {"name": "size", "display_name": "Small Solitary Focus", "score": 0.22, "level": "low", "description": "4.5 mm smooth baseline nodule with low pre-test probability"},
                    ],
                    "is_demo": True,
                },
            },
        ],
        "summary": {
            "nodule_count": 3,
            "largest_nodule_mm": 14.2,
            "highest_risk_pct": 78.0,
            "lung_rads_overall": "4X",
            "conclusion": "Three distinct pulmonary nodules representing a mixed risk spectrum: Dominant Nodule #1 (14.2 mm, High Risk 78.0%, Lung-RADS 4X), Nodule #2 (8.2 mm, Intermediate 34.0%, Lung-RADS 4A), and Nodule #3 (4.5 mm, Low Risk 8.0%, Lung-RADS 2).",
        },
    },
}


class DemoAIService:
    """Returns DEMO DATA for all AI pipeline stages from unified single source of truth."""
    DEMO_CASES = DEMO_CASES

    def get_demo_case(self, demo_case_id: str) -> Optional[Dict[str, Any]]:
        return DEMO_CASES.get(demo_case_id)

    def list_demo_cases(self) -> List[Dict[str, Any]]:
        return [
            {
                "id": k,
                "label": v["label"],
                "description": v["description"],
                "scenario": v.get("scenario"),
                "primary_risk_category": v.get("primary_risk_category"),
                "dominant_size_mm": v.get("dominant_size_mm"),
                "nodule_count": v["summary"]["nodule_count"],
                "highest_risk_pct": v["summary"]["highest_risk_pct"],
                "lung_rads_overall": v["summary"]["lung_rads_overall"],
                "input_type": v.get("input_type", "volumetric_ct"),
                "analysis_mode": v.get("analysis_mode", "demo"),
            }
            for k, v in DEMO_CASES.items()
        ]

    def simulate_pipeline_stages(self) -> list:
        return [
            {"key": "upload_received", "label": "Upload received"},
            {"key": "dicom_validation", "label": "DICOM validation"},
            {"key": "volume_reconstruction", "label": "3D volume reconstruction"},
            {"key": "lung_segmentation", "label": "Lung segmentation"},
            {"key": "nodule_detection", "label": "Nodule detection"},
            {"key": "nodule_segmentation", "label": "Nodule segmentation"},
            {"key": "feature_extraction", "label": "Feature extraction"},
            {"key": "risk_assessment", "label": "Risk assessment"},
            {"key": "report_generation", "label": "Report generation"},
        ]


demo_ai_service = DemoAIService()
