"""Report generation service with PDF export via ReportLab."""
import os
import io
import uuid
from datetime import datetime
from typing import Optional
from sqlalchemy.orm import Session
from app.models.case import Case, Report, Nodule

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


DENSITY_LABELS = {
    "solid": "Solid",
    "part_solid": "Part-solid",
    "ground_glass": "Ground-glass",
    "calcified": "Calcified",
    "unknown": "Unknown",
}

LOBE_LABELS = {
    "RUL": "Right Upper Lobe",
    "RML": "Right Middle Lobe",
    "RLL": "Right Lower Lobe",
    "LUL": "Left Upper Lobe",
    "LLL": "Left Lower Lobe",
    "unknown": "Unknown",
}


class ReportService:
    def __init__(self, db: Session):
        self.db = db

    def generate(self, case: Case) -> Report:
        """Generate a structured AI-assisted report for a case."""
        existing = self.db.query(Report).filter(Report.case_id == case.id).first()
        if existing and existing.report_text:
            return existing

        nodules = case.nodules or []
        sm = case.scan_metadata

        # Build structured plain-text report
        lines = [
            "PULMOSCAN AI",
            "AI-ASSISTED PULMONARY NODULE ANALYSIS REPORT",
            "=" * 60,
            "",
            "⚠  RESEARCH PROTOTYPE — NOT A CLINICAL DIAGNOSTIC SYSTEM",
            "This report is generated by an AI research prototype for",
            "decision-support demonstration only. It is not a substitute",
            "for assessment by a qualified medical professional.",
            "",
            "=" * 60,
            "STUDY INFORMATION",
            "=" * 60,
            f"Case ID:        {case.case_id}",
            f"Generated:      {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        ]

        if sm:
            lines += [
                f"Modality:       {sm.modality}",
                f"Patient ID:     {sm.patient_id_anon}",
                f"Study Date:     {sm.study_date or 'Unknown'}",
                f"Series:         {sm.series_description or 'Unknown'}",
                f"Slices:         {sm.slice_count or 'Unknown'}",
                f"Slice Thickness:{sm.slice_thickness_mm or 'Unknown'} mm",
                f"Scan Quality:   {sm.scan_quality.upper()}",
            ]

        lines += ["", "=" * 60, "AI FINDINGS", "=" * 60]

        analysis_mode = getattr(case, "analysis_mode", "volumetric_ct")
        if analysis_mode == "image_review":
            lines += [
                "MODE: 2D Visual Review (Photo / Medical Image)",
                "------------------------------------------------------------",
                "• Study submitted as a 2D photograph / image for visual review.",
                "• Quantitative 3D volumetric CT analysis, Hounsfield Unit statistics,",
                "  and voxel measurements are not applicable to 2D images.",
                "• For 3D pulmonary nodule detection, segmentation, and Lung-RADS",
                "  risk estimation, upload a calibrated volumetric DICOM or NIfTI series.",
            ]
        elif analysis_mode == "video_review":
            lines += [
                "MODE: Visual Review (CT Cine Video)",
                "------------------------------------------------------------",
                "• Study submitted as a CT cine / video recording for visual review.",
                "• Quantitative 3D voxel reconstruction, calibrated Hounsfield Unit",
                "  statistics, and volume doubling kinetics require a calibrated",
                "  volumetric DICOM or NIfTI series.",
            ]
        elif not nodules:
            lines.append("No suspicious pulmonary nodules detected by the AI system.")
            lines.append("Overall ACR Lung-RADS Category: 1 (Negative)")
        else:
            lines.append(f"{len(nodules)} pulmonary nodule(s) detected and analyzed (Prototype Analysis).")
            lines.append("")
            for n in nodules:
                lobe = LOBE_LABELS.get(n.lung_lobe or "unknown", "Unknown")
                density = DENSITY_LABELS.get(n.density_type or "unknown", "Unknown")
                lines += [
                    f"NODULE #{n.nodule_index}",
                    f"  Detection confidence:  {int((n.detection_confidence or 0) * 100)}%",
                    f"  Location:              {lobe} ({n.position_type or 'peripheral'})",
                    f"  Maximum diameter:      {n.max_diameter_mm or '--'} mm",
                    f"  Volume:                {n.volume_mm3 or '--'} mm³",
                    f"  Density:               {density} (Mean HU: {n.mean_hu or '--'})",
                    f"  Margin:                {(n.margin_type or 'Unknown').capitalize()}",
                    f"  Spiculation:           {'Detected' if n.spiculation_detected else 'Not detected'}",
                    "",
                ]

                if n.risk_assessments:
                    r = n.risk_assessments[0]
                    risk_pct = round((r.risk_probability or 0) * 100, 1)
                    lines += [
                        f"  RISK ASSESSMENT (Evidence-based Brock Model):",
                        f"  Estimated malignancy probability: {risk_pct}% ({r.risk_category or 'Unknown'})",
                        f"  ACR Lung-RADS category:           Category {r.lung_rads_category or 'N/A'}",
                        f"  Suggested follow-up:             {r.lung_rads_recommendation or 'N/A'}",
                        "",
                    ]

        lines += [
            "=" * 60,
            "AI LIMITATIONS & DISCLAIMER",
            "=" * 60,
            "• This system is a research prototype and is NOT a cleared diagnostic medical device.",
            "• Measurements and segmentation contours are AI-assisted estimates.",
            "• Malignancy probability is derived from multivariable logistic models (Brock/PanCan).",
            "• All findings require independent verification by a licensed thoracic radiologist.",
            "",
            "PulmoScan AI Platform — Prototype v0.1",
        ]

        report_text = "\n".join(lines)

        report_data = {
            "case_id": case.case_id,
            "is_demo": case.is_demo,
            "nodule_count": len(nodules),
            "generated_at": datetime.utcnow().isoformat(),
            "highest_risk_category": "low",
        }
        if nodules:
            all_risks = [
                n.risk_assessments[0].risk_probability
                for n in nodules
                if n.risk_assessments and n.risk_assessments[0].risk_probability
            ]
            if all_risks:
                report_data["highest_risk_pct"] = round(max(all_risks) * 100, 1)

        pdf_path = None
        if HAS_REPORTLAB:
            try:
                pdf_dir = "./data/reports"
                os.makedirs(pdf_dir, exist_ok=True)
                pdf_filename = f"{case.case_id}_report.pdf"
                pdf_path = os.path.join(pdf_dir, pdf_filename)
                self.build_pdf(pdf_path, case, report_text)
            except Exception as e:
                import traceback
                traceback.print_exc()
                pdf_path = None

        if existing:
            existing.report_text = report_text
            existing.report_data = report_data
            existing.pdf_path = pdf_path
            self.db.commit()
            return existing

        report = Report(
            id=str(uuid.uuid4()),
            case_id=case.id,
            report_text=report_text,
            report_data=report_data,
            pdf_path=pdf_path,
            is_demo=case.is_demo,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        self.db.commit()
        self.db.refresh(report)
        return report

    def build_pdf(self, output_path: str, case: Case, report_text: str):
        """Construct a high-quality PDF report with ReportLab."""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#0f172a"),
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748b"),
        )
        h2_style = ParagraphStyle(
            "Heading2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#1e293b"),
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#b45309"),
            spaceBefore=10,
        )

        elements = []

        # Header Title
        elements.append(Paragraph("PULMOSCAN AI", title_style))
        elements.append(Paragraph("AI-Assisted Pulmonary Nodule Assessment & Quantitative Analysis", subtitle_style))
        elements.append(Spacer(1, 10))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0ea5e9"), spaceAfter=12))

        # Study Info Table
        sm = case.scan_metadata
        modality_str = (sm.modality if sm and sm.modality else "CT")
        series_str = (sm.series_description if sm and sm.series_description else "Thoracic CT")
        slices_str = str(sm.slice_count if sm and sm.slice_count is not None else 0)
        spacing_str = f"{(sm.slice_thickness_mm if sm and sm.slice_thickness_mm is not None else 1.25)} mm"

        study_info = [
            [Paragraph("<b>Case ID:</b>", body_style), Paragraph(str(case.case_id or "UNKNOWN"), body_style),
             Paragraph("<b>Date:</b>", body_style), Paragraph(datetime.utcnow().strftime("%Y-%m-%d"), body_style)],
            [Paragraph("<b>Modality:</b>", body_style), Paragraph(modality_str, body_style),
             Paragraph("<b>Series:</b>", body_style), Paragraph(series_str, body_style)],
            [Paragraph("<b>Slices:</b>", body_style), Paragraph(slices_str, body_style),
             Paragraph("<b>Slice Spacing:</b>", body_style), Paragraph(spacing_str, body_style)],
        ]
        info_table = Table(study_info, colWidths=[80, 180, 80, 200])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#f1f5f9")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 14))

        # Findings
        analysis_mode = getattr(case, "analysis_mode", "volumetric_ct")
        if analysis_mode == "image_review":
            elements.append(Paragraph("2D VISUAL REVIEW (IMAGE / PHOTO)", h2_style))
            elements.append(Paragraph(
                "This study was submitted as a 2D medical photograph or image for visual review. "
                "Quantitative 3D volumetric CT analysis, calibrated Hounsfield Unit statistics, and voxel measurements "
                "are not applicable to 2D images. For 3D pulmonary nodule segmentation and Lung-RADS risk scoring, "
                "please upload a calibrated volumetric DICOM or NIfTI CT series.",
                body_style
            ))
            elements.append(Spacer(1, 14))
        elif analysis_mode == "video_review":
            elements.append(Paragraph("VISUAL REVIEW (CT CINE VIDEO)", h2_style))
            elements.append(Paragraph(
                "This study was submitted as a CT cine / video recording for visual inspection. "
                "Quantitative 3D voxel reconstruction, calibrated Hounsfield Unit statistics, and volume doubling kinetics "
                "require a calibrated volumetric DICOM or NIfTI CT series.",
                body_style
            ))
            elements.append(Spacer(1, 14))
        else:
            elements.append(Paragraph("QUANTITATIVE AI FINDINGS", h2_style))
            nodules = case.nodules or []
            if not nodules:
                elements.append(Paragraph("No suspicious pulmonary nodules identified.", body_style))
            else:
                table_data = [
                    ["#", "Lobe", "Diam (mm)", "Volume (mm³)", "Density", "Mean HU", "Risk Est.", "Lung-RADS"]
                ]
            for n in nodules:
                r_pct = "--"
                lrads = "--"
                if n.risk_assessments:
                    r = n.risk_assessments[0]
                    r_pct = f"{int((r.risk_probability or 0) * 100)}%"
                    lrads = f"Cat {r.lung_rads_category or 'N/A'}"

                table_data.append([
                    str(n.nodule_index),
                    n.lung_lobe or "Unknown",
                    f"{n.max_diameter_mm or '--'}",
                    f"{n.volume_mm3 or '--'}",
                    DENSITY_LABELS.get(n.density_type, n.density_type or "--"),
                    f"{n.mean_hu or '--'}",
                    r_pct,
                    lrads,
                ])

            findings_table = Table(table_data, colWidths=[25, 60, 65, 75, 75, 60, 75, 85])
            findings_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 5),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("TOPPADDING", (0, 1), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
            ]))
            elements.append(findings_table)

        elements.append(Spacer(1, 14))

        # Risk and Recommendations
        elements.append(Paragraph("CLINICAL RECOMMENDATIONS & LUNG-RADS GUIDANCE", h2_style))
        for n in nodules:
            if n.risk_assessments:
                r = n.risk_assessments[0]
                rec_text = (
                    f"<b>Nodule #{n.nodule_index} ({n.lung_lobe}, {n.max_diameter_mm} mm):</b> "
                    f"Estimated malignancy risk is {int((r.risk_probability or 0) * 100)}% ({r.risk_category or 'low'}). "
                    f"Assigned ACR Lung-RADS {r.lung_rads_category or 'N/A'}. Guidance: {r.lung_rads_recommendation or 'Clinical correlation recommended.'}"
                )
                elements.append(Paragraph(rec_text, body_style))
                elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 16))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=10))

        # Disclaimer
        disclaimer_box = (
            "<b>NOTICE:</b> This report is generated by PulmoScan AI, an investigational decision-support tool. "
            "It is not cleared as a primary diagnostic device. All findings, segmentation contours, and risk "
            "scores must be reviewed and confirmed by a certified physician or radiologist."
        )
        elements.append(Paragraph(disclaimer_box, disclaimer_style))

        doc.build(elements)


report_service_instance = None
